# .github/workflows/update_demonlist.yml
name: 햇햤햣햢햫햣쒫쫧쮏 쮏쐃쫧쮏쒫햣햫햦햣 Demonlist

on:
  schedule:
    - cron: '0 21 * * *'  # 햨햟햤햢혦햧 햢햣햫혧  5:00 UTC
  workflow_dispatch:

permissions:
  contents: write   # 游녣 햢햟햣혝 GitHub Actions 햟향햣혣햣햫햦햣 햫햟 혞혣 햦향햪햣햫햣햫햦햧

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 游녣 쮏쐄향햟혝햣햩혧햫 햣햣햢햟햣햪 혝쮏쥃왏

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright browsers and dependencies
        run: playwright install --with-deps

      - name: Run data scraper with virtual display
        run: xvfb-run python update_data.py

      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(auto): 游댃 햇햤햣햢햫햣쒫쫧쮏 쮏쐃쫧쮏쒫햣햫햦햣 햢햟햫햫혦혠 Demonlist"
          file_pattern: data/demonlist.json
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: JustKingYT1 <JustKingYT1@users.noreply.github.com>
